//////////////////////////////////////////////////////////////////////////////
// Module       : pwm25_generator
// Description  : 25路PWM生成器，用于5x5超声换能器阵列驱动
//                每路可独立控制相位和幅度，支持ADC包络调制
// Features     :
//   - 系统时钟50MHz，载波频率40kHz
//   - 25路独立PWM输出，每路可独立设置相位和幅度
//   - 相位分辨率：360/1024 = 0.35度
//   - 幅度分辨率：8位(0~255)，通过占空比控制
//   - 支持ADC包络调制：envelope * amplitude >> 8
//   - 共享乘法器设计，资源优化
//   - 32位对齐输出，方便送595移位寄存器
// Author       : Generated by AI Assistant
// Date         : 2024
// Standard     : Verilog-2001
//////////////////////////////////////////////////////////////////////////////

module pwm25_generator (
    input        clk,       // 50MHz系统时钟
    input        rst_n,     // 低电平复位，异步复位
    input        en,        // 模块使能（高电平有效）

    // 载波基准输入
    input        carrier_tick,      // 40kHz载波周期标记（每载波周期一个脉冲）
    input [10:0] carrier_period,    // 载波周期值（默认1250 = 50MHz/40kHz）

    // 波束控制参数（每路独立，param_valid时锁存）
    input [7:0]  amplitude [0:24],  // 25路幅度值 (0~255，255=满幅度)
    input [9:0]  phase     [0:24],  // 25路相位偏移 (0~1023，360度对应1024)
    input        param_valid,       // 参数更新有效（高电平脉冲，触发参数锁存）

    // 调制包络输入（envelope_valid时更新）
    input [7:0]  envelope,          // ADC envelope (0~255)
    input        envelope_valid,    // 包络有效（高电平脉冲）

    // PWM输出
    output reg [24:0] pwm_out,      // 25路PWM输出（低25位有效，位[i]对应第i路）
    output reg [31:0] pwm_out_32bit // 32位对齐输出（高7位补零），方便送595驱动器
);

    //========================================================================
    // 参数定义
    //========================================================================
    parameter CH_NUM        = 25;    // 通道数量（5x5阵列）
    parameter CNT_WIDTH     = 11;    // 载波计数器位宽（0~1249需要11位）
    parameter PHASE_WIDTH   = 10;    // 相位位宽（0~1023对应0~360度）
    parameter AMP_WIDTH     = 8;     // 幅度/占空比位宽（0~255）
    parameter DEFAULT_PERIOD = 1250; // 默认载波周期：50MHz/40kHz

    // 计算状态机编码
    localparam IDLE       = 2'd0;   // 空闲状态
    localparam CALC_PHASE = 2'd1;   // 计算相位延迟（phase -> 时钟周期数）
    localparam CALC_DUTY  = 2'd2;   // 计算调制后的占空比

    //========================================================================
    // 内部信号/寄存器声明
    //========================================================================

    // --- 载波相关 ---
    reg [CNT_WIDTH-1:0] carrier_cnt;         // 载波计数器：0 ~ carrier_period_reg-1
    reg [CNT_WIDTH-1:0] carrier_period_reg;  // 锁存的载波周期值（整个周期保持不变）

    // --- 25路参数寄存器（param_valid时从输入锁存）---
    reg [AMP_WIDTH-1:0]   amp_reg   [0:CH_NUM-1];  // 25路幅度寄存器
    reg [PHASE_WIDTH-1:0] phase_reg [0:CH_NUM-1];  // 25路相位寄存器

    // --- 包络寄存器（envelope_valid时更新）---
    reg [AMP_WIDTH-1:0] env_reg;       // 当前包络值

    // --- 预计算结果（计算完成后用于PWM生成）---
    reg [CNT_WIDTH-1:0] phase_delay [0:CH_NUM-1];  // 相位延迟映射到时钟周期数
    reg [AMP_WIDTH-1:0] duty_reg    [0:CH_NUM-1];  // 调制后的归一化占空比(0~255)

    // --- 计算状态机 ---
    reg [1:0]  calc_state;         // 计算状态机当前状态
    reg [4:0]  calc_cnt;           // 计算通道计数器：0~24

    // --- 请求缓存（计算忙碌时缓存新请求）---
    reg param_pending;             // 有挂起的参数更新请求
    reg envelope_pending;          // 有挂起的包络更新请求
    reg [AMP_WIDTH-1:0] pending_envelope;  // 缓存的包络值

    // --- 共享乘法器（资源优化：25路共享1个乘法器）---
    reg  [PHASE_WIDTH-1:0] mult_a;  // 乘法器A输入（最大10位）
    reg  [CNT_WIDTH-1:0]   mult_b;  // 乘法器B输入（最大11位）
    wire [PHASE_WIDTH+CNT_WIDTH-1:0] mult_result;  // 乘法结果（21位）

    // --- PWM输出中间信号 ---
    wire [CH_NUM-1:0] pwm_next;    // 25路PWM下一状态（组合逻辑输出）

    // --- 循环变量 ---
    integer i;

    //========================================================================
    // 组合逻辑：共享乘法器
    // 在CALC_PHASE状态计算 phase * carrier_period
    // 在CALC_DUTY  状态计算 amplitude * envelope
    //========================================================================
    assign mult_result = mult_a * mult_b;

    //========================================================================
    // 载波计数器
    // 功能：在每个50MHz时钟加1，carrier_tick到来时清零
    // 范围：0 ~ carrier_period_reg-1（默认0~1249）
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            carrier_cnt <= {CNT_WIDTH{1'b0}};
        else if (!en)
            carrier_cnt <= {CNT_WIDTH{1'b0}};
        else if (carrier_tick)
            carrier_cnt <= {CNT_WIDTH{1'b0}};  // 新载波周期开始，清零
        else
            carrier_cnt <= carrier_cnt + 1'b1;  // 正常计数
    end

    //========================================================================
    // 载波周期锁存
    // 功能：在carrier_tick上升沿锁存carrier_period输入
    // 目的：保证整个载波周期内carrier_period_reg值不变
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            carrier_period_reg <= DEFAULT_PERIOD[10:0];  // 默认1250
        else if (carrier_tick)
            carrier_period_reg <= carrier_period;         // 锁存新周期值
    end

    //========================================================================
    // 请求缓存逻辑
    // 功能：当计算状态机忙碌(CALC_PHASE或CALC_DUTY)时，
    //       缓存新到来的param_valid和envelope_valid请求
    // 注意：假设外部在param_valid时会保持amplitude/phase值稳定
    //       直到参数被处理完毕
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            param_pending    <= 1'b0;
            envelope_pending <= 1'b0;
            pending_envelope <= {AMP_WIDTH{1'b0}};
        end
        else if (!en) begin
            param_pending    <= 1'b0;
            envelope_pending <= 1'b0;
        end
        else begin
            // 仅在非IDLE状态时缓存请求
            if (calc_state != IDLE) begin
                if (param_valid) begin
                    param_pending    <= 1'b1;
                    pending_envelope <= envelope;
                end
                if (envelope_valid) begin
                    envelope_pending <= 1'b1;
                    pending_envelope <= envelope;
                end
            end
            // IDLE状态时清除已处理的pending请求
            else begin
                if (param_pending)
                    param_pending <= 1'b0;
                if (envelope_pending)
                    envelope_pending <= 1'b0;
            end
        end
    end

    //========================================================================
    // 参数更新与计算状态机
    //========================================================================
    // 功能：响应param_valid和envelope_valid，计算25路的phase_delay和duty
    //
    // 状态转换：
    //   param_valid:   IDLE -> CALC_PHASE -> CALC_DUTY -> IDLE  (共50周期)
    //   envelope_valid: IDLE -> CALC_DUTY -> IDLE               (共25周期)
    //
    // 共享乘法器时序：
    //   组合逻辑设置mult_a/mult_b -> 本周期mult_result有效
    //   -> 下一时钟上升沿保存结果到phase_delay/duty_reg
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // 复位所有状态
            calc_state <= IDLE;
            calc_cnt   <= 5'd0;
            env_reg      <= {AMP_WIDTH{1'b0}};

            // 复位25路参数
            for (i = 0; i < CH_NUM; i = i + 1) begin
                amp_reg[i]     <= {AMP_WIDTH{1'b0}};
                phase_reg[i]   <= {PHASE_WIDTH{1'b0}};
                phase_delay[i] <= {CNT_WIDTH{1'b0}};
                duty_reg[i]    <= {AMP_WIDTH{1'b0}};
            end
        end
        else if (!en) begin
            calc_state <= IDLE;
            calc_cnt   <= 5'd0;
        end
        else begin
            case (calc_state)

                //--------------------------------------------------------
                // IDLE: 空闲状态，等待参数更新请求
                // 优先级：param_valid > envelope_valid
                //--------------------------------------------------------
                IDLE: begin
                    calc_cnt <= 5'd0;

                    // 优先处理挂起的param请求
                    if (param_pending) begin
                        // 外部需保持amplitude/phase稳定到pending请求被处理
                        for (i = 0; i < CH_NUM; i = i + 1) begin
                            amp_reg[i]   <= amplitude[i];
                            phase_reg[i] <= phase[i];
                        end
                        env_reg      <= pending_envelope;
                        calc_state   <= CALC_PHASE;
                    end
                    // 处理挂起的envelope请求
                    else if (envelope_pending) begin
                        env_reg      <= pending_envelope;
                        calc_state   <= CALC_DUTY;
                    end
                    // 处理新的param_valid请求
                    else if (param_valid) begin
                        // 立即锁存25路amplitude和phase
                        for (i = 0; i < CH_NUM; i = i + 1) begin
                            amp_reg[i]   <= amplitude[i];
                            phase_reg[i] <= phase[i];
                        end
                        env_reg      <= envelope;
                        calc_state   <= CALC_PHASE;
                    end
                    // 处理新的envelope_valid请求
                    else if (envelope_valid) begin
                        env_reg      <= envelope;
                        calc_state   <= CALC_DUTY;
                    end
                end

                //--------------------------------------------------------
                // CALC_PHASE: 计算25路相位延迟
                // 公式: phase_delay[i] = (phase_reg[i] * carrier_period_reg) >> 10
                //      = phase_reg[i] * carrier_period_reg / 1024
                // 说明：将0~1023的相位映射到0~carrier_period的时钟周期数
                //       每时钟计算1路，25个时钟完成
                //--------------------------------------------------------
                CALC_PHASE: begin
                    // mult_result[20:10] = (phase * carrier_period) / 1024
                    // 取乘法结果的高11位，即右移10位
                    phase_delay[calc_cnt] <= mult_result[20:10];

                    if (calc_cnt == (CH_NUM - 1)) begin
                        // 25路phase_delay计算完成，进入占空比计算
                        calc_cnt <= 5'd0;
                        calc_state <= CALC_DUTY;
                    end
                    else begin
                        calc_cnt <= calc_cnt + 1'b1;
                    end
                end

                //--------------------------------------------------------
                // CALC_DUTY: 计算25路调制后的归一化占空比
                // 公式: duty[i] = (amp_reg[i] * env_reg) >> 8
                //      = amp_reg[i] * envelope / 256
                // 说明：幅度与包络相乘后取高8位，得到0~255归一化占空比
                //       PWM生成阶段再映射到0~carrier_period/2个时钟
                //       每时钟计算1路，25个时钟完成
                //--------------------------------------------------------
                CALC_DUTY: begin
                    // mult_result[15:8] = (amplitude * envelope) / 256
                    // 取乘法结果的高8位，即右移8位
                    if ((amp_reg[calc_cnt] == 8'hFF) && (env_reg == 8'hFF))
                        duty_reg[calc_cnt] <= 8'hFF;
                    else
                        duty_reg[calc_cnt] <= mult_result[15:8];

                    if (calc_cnt == (CH_NUM - 1)) begin
                        // 25路duty计算完成，返回IDLE
                        calc_state <= IDLE;
                    end
                    else begin
                        calc_cnt <= calc_cnt + 1'b1;
                    end
                end

                //--------------------------------------------------------
                // 默认状态：安全返回IDLE
                //--------------------------------------------------------
                default: calc_state <= IDLE;

            endcase
        end
    end

    //========================================================================
    // 组合逻辑：共享乘法器输入选择
    // 根据当前计算状态为mult_a/mult_b赋值
    //========================================================================
    always @(*) begin
        case (calc_state)

            CALC_PHASE: begin
                // 计算相位延迟：phase_delay = phase * carrier_period / 1024
                // mult_a = 10位相位值，mult_b = 11位载波周期值
                mult_a = phase_reg[calc_cnt];
                mult_b = carrier_period_reg;
            end

            CALC_DUTY: begin
                // 计算占空比：duty = amplitude * envelope / 256
                // 将8位幅度扩展为10位，8位包络扩展为11位
                // 乘法结果中取[15:8]即为除以256后的高8位
                mult_a = {2'b00, amp_reg[calc_cnt]};  // 8位->10位
                mult_b = {3'b000, env_reg};            // 8位->11位
            end

            default: begin
                mult_a = {PHASE_WIDTH{1'b0}};
                mult_b = {CNT_WIDTH{1'b0}};
            end

        endcase
    end

    //========================================================================
    // 25路PWM生成（Generate生成25个独立通道）
    //========================================================================
    // 每路工作原理：
    //   1. 计算有效计数器：eff_cnt = (carrier_cnt + phase_delay) % carrier_period
    //   2. 产生PWM原始信号：pwm_raw = (eff_cnt < duty) ? 1 : 0
    //   3. 输出PWM：相位只由phase_delay控制，envelope只控制duty
    //
    // 取模运算实现：
    //   carrier_cnt + phase_delay 最大为 1249 + 1249 = 2498
    //   如果和 >= carrier_period，减去carrier_period即可
    //========================================================================
    genvar gi;
    generate
        for (gi = 0; gi < CH_NUM; gi = gi + 1) begin : pwm_channel

            // 有效计数器 = carrier_cnt + phase_delay（12位防止溢出）
            wire [CNT_WIDTH:0] eff_cnt_sum;
            assign eff_cnt_sum = {1'b0, carrier_cnt} + {1'b0, phase_delay[gi]};

            // 取模运算：如果和 >= carrier_period，减去carrier_period
            wire [CNT_WIDTH-1:0] eff_cnt;
            assign eff_cnt = (eff_cnt_sum >= {1'b0, carrier_period_reg}) ?
                              (eff_cnt_sum - {1'b0, carrier_period_reg}) :
                               eff_cnt_sum[CNT_WIDTH-1:0];

            // 将0~255归一化占空比映射到0~carrier_period/2个时钟
            // 满幅接近50%占空比，避免100%直流输出破坏40kHz载波分量
            wire [CNT_WIDTH-1:0] half_period;
            wire [CNT_WIDTH+AMP_WIDTH-1:0] duty_scaled;
            wire [CNT_WIDTH-1:0] duty_ext;
            assign half_period = carrier_period_reg >> 1;
            assign duty_scaled = duty_reg[gi] * half_period;
            assign duty_ext = duty_scaled[CNT_WIDTH+AMP_WIDTH-1:AMP_WIDTH];

            // PWM原始输出：有效计数器 < 占空比时输出高电平
            wire pwm_raw;
            assign pwm_raw = (eff_cnt < duty_ext);

            assign pwm_next[gi] = pwm_raw;

        end
    endgenerate

    //========================================================================
    // PWM输出寄存器（时序逻辑）
    // 在时钟上升沿更新pwm_out，避免毛刺
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            pwm_out <= {CH_NUM{1'b0}};
        else if (!en)
            pwm_out <= {CH_NUM{1'b0}};
        else
            pwm_out <= pwm_next;
    end

    //========================================================================
    // 32位对齐输出（时序逻辑）
    // 格式: {7'b0, pwm_out[24:0]} = 32位，高7位补零
    // 用途: 方便直接送74HC595等串行移位寄存器驱动
    //========================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            pwm_out_32bit <= 32'd0;
        else
            pwm_out_32bit <= {{(32-CH_NUM){1'b0}}, pwm_next};
    end

endmodule
